CREATE TABLE pda_prouni_2005(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20)
);