CREATE TABLE pda_prouni_2006(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);