-- All of the tables for years 2008-2019 have the same fields and datatypes, which is why they are created in a single file

CREATE TABLE pda_prouni_2008(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2009(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2010(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2011(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2012(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2013(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2014(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2015(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2016(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2017(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2018(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);

CREATE TABLE pda_prouni_2019(
ANO_CONCESSAO_BOLSA INT,
CODIGO_EMEC_IES_BOLSA INT,
NOME_IES_BOLSA VARCHAR(200),
TIPO_BOLSA VARCHAR(50),
MODALIDADE_ENSINO_BOLSA VARCHAR(20),
NOME_CURSO_BOLSA VARCHAR(20),
NOME_TURNO_CURSO_BOLSA VARCHAR(20),
CPF_BENEFICIARIO_BOLSA VARCHAR(20),
SEXO_BENEFICIARIO_BOLSA VARCHAR(20),
RACA_BENEFICIARIO_BOLSA VARCHAR(15),
DT_NASCIMENTO_BENEFICIARIO VARCHAR(20),
BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(10),
REGIAO_BENEFICIARIO_BOLSA VARCHAR(15),
SIGLA_UF_BENEFICIARIO_BOLSA VARCHAR(5),
MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(50)
);
